### PR TITLE
Status fifo queue

### LINKED ISSUE #490: [LUNATIX] Lunatix - Stack at initial splash screen, can't progress into game
**Module Information**
* LUNATIX
* Lunatix
* 5.3f

**Describe the bug**
Can't get past intro screen after launching game. Feels like a regression as this used to work in https://github.com/mbbsemu/MBBSEmu/releases/tag/v1.0-alpha-010421

**To Reproduce**
1. Launch MBBSEmu
2. Either telnet/rlogin into the MBBSEmu menu _or_ directly to the rlogin game port for Lunatix
3. See ansi splash screen/info screen
4. Press enter or any other key to continue and note that you're stuck at this screen

**Expected behavior**
Game logic continues and allows you to either create a character (if you haven't already) or continue gaming from previous login

**Screenshots**
image

**Software Information:**
- OS: Ubuntu 20.04 amd64
- Telnet Client: NetRunner as well as linux telnet and linux rlogin

### PR DESCRIPTION
**Pull request by enusbaum**
Change Status from a `ushort` to a `Queue<ushort>`. MajorBBS modules can inject status codes using `btuinj` while still also manually setting `STATUS` to `1` (ok) after `sttrout` runs, which would have previously overwritten the injected status. Moving to a queue means we no longer need to track if a status has "changed", we just process what's in the queue.

Fixes #490

### CODE REVIEW

File: MBBSEmu/HostProcess/HostRoutines/MenuRoutines.cs [hunk 1]
```diff
@@ -225,8 +224,7 @@ private void LoginPasswordDisplay(SessionBase session)
         private void LoginPasswordInput(SessionBase session)
         {
             //Only Process on CR
-            if (session.Status != 3) return;
-            session.Status = 0;
+            if (session.GetStatus() != 3) return;
```
Comment (paladine) [inline MBBSEmu/HostProcess/HostRoutines/MenuRoutines.cs:227]: we really need to use some enums here to get rid of these magic number statuses

**Review by paladine — APPROVED** [review]
